version: '1.0.0-pre-{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
configuration: Release
platform:
  - Any CPU

environment:
  NUGET_API_KEY:
    secure: UNhG2ePtkOWC4kyxRzHWPVYv5GM+QgT1/8S3aVsU3Vyrhag1VnzaN7jUe7vxcZZJ
branches:
  only:
    - master
    - develop
    - /v\d*\.\d*\.\d*/

#clone_folder: /var/appveyor/umfrage

init:
  - ps: git config --global core.autocrlf input
  - ps: dotnet nuget locals http-cache -c

before_build:
  - ps: ls
  - ps: dotnet restore

build_script:
  - ps: dotnet build src/Umfrage/Umfrage.csproj --verbosity m
  - ps: dotnet build src/Umfrage.Extensions/Umfrage.Extensions.csproj --verbosity m

test_script:
  - ps: dotnet test test/Umfrage.Test/Umfrage.Test.csproj --verbosity normal

after_test:
  - ps: dotnet pack src/Umfrage/Umfrage.csproj -c Release -o publish
  - ps: dotnet pack src/Umfrage.Extensions/Umfrage.Extensions.csproj -c Release -o publish

deploy:
  provider: NuGet
  api_key:
    secure: UNhG2ePtkOWC4kyxRzHWPVYv5GM+QgT1/8S3aVsU3Vyrhag1VnzaN7jUe7vxcZZJ
  artifact: /.*\.nupkg/
