version: '1.0.0-pre-{build}'
image: Ubuntu
skip_branch_with_pr: true
configuration: Release
platform: 
  - x64
  - Any CPU

environment:
  NUGET_API_KEY:
    secure: UNhG2ePtkOWC4kyxRzHWPVYv5GM+QgT1/8S3aVsU3Vyrhag1VnzaN7jUe7vxcZZJ
branches:
  only:
    - master
    - develop
    - /v\d*\.\d*\.\d*/
init:
  - sh: dir
  - sh: dotnet nuget locals http-cache -c

before_build:
  - sh: dotnet restore

build_script:
  - sh: dotnet build src/Umfrage/Umfrage.csproj --verbosity m
  - sh: dotnet build src/Umfrage.Extensions/Umfrage.Extensions.csproj --verbosity m

test_script:
  - sh: dotnet test test/Umfrage.Test/Umfrage.Test.csproj --verbosity normal

deploy:
  - provider: NuGet
  - api_key:
      - secure: UNhG2ePtkOWC4kyxRzHWPVYv5GM+QgT1/8S3aVsU3Vyrhag1VnzaN7jUe7vxcZZJ
  - skip_symbols: false
  - symbol_server:           # remove to push symbols to SymbolSource.org
  - artifact: /.*\.nupkg/
