version: '1.0.0-pre-{build}'
image: Ubuntu
skip_branch_with_pr: true
configuration: Release
platform:
  - Any CPU

environment:
  NUGET_API_KEY:
    secure: UNhG2ePtkOWC4kyxRzHWPVYv5GM+QgT1/8S3aVsU3Vyrhag1VnzaN7jUe7vxcZZJ
branches:
  only:
    - master
    - develop
    - /v\d*\.\d*\.\d*/

clone_folder: /var/appveyor/umfrage

init:
  - git config --global core.autocrlf input
  - ls
  - dotnet nuget locals http-cache -c

before_build:
  - ls
  - dotnet restore

build_script:
  - dotnet build src/Umfrage/Umfrage.csproj --verbosity m
  - dotnet build src/Umfrage.Extensions/Umfrage.Extensions.csproj --verbosity m

test_script:
  - dotnet test test/Umfrage.Test/Umfrage.Test.csproj --verbosity normal

deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: $NUGET_API_KEY
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
