version: '1.0-{build}'
image: Visual Studio 2019
skip_branch_with_pr: true
configuration: Release
platform: x64
init:
  - ps: ls
  - ps: dotnet nuget locals http-cache -c
before_build:
  - ps: dotnet restore
build_script:
  - ps: ls
  - ps: dotnet build src/Umfrage.csproj --verbosity m
  - ps: dotnet build src/Umfrage.Extensions.csproj --verbosity m
test_script:
  - ps: ls
  - ps: dotnet test tests/Umfrage.Test.csproj --verbosity normal

